[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor -T partitions.csv -L defmt"

[env]
ESP_LOGL="debug"
DEFMT_LOG="debug"

[build]
target = "xtensa-esp32-none-elf"

[unstable]
build-std = ["alloc", "core"]
