[build]
target = "xtensa-esp32-espidf"
rustflags = [ "--cfg",  "espidf_time64"] # Extending time_t for ESP IDF 5: https://github.com/esp-rs/rust/issues/110

[target.xtensa-esp32-espidf]
linker = "ldproxy"
runner = "espflash flash --monitor --bootloader ../target/xtensa-esp32-espidf/release/bootloader.bin --partition-table partitions.csv" # Select this runner for espflash v3.x.x

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU="esp32"
# Note: this variable is not used by the pio builder (`cargo build --features pio`)
ESP_IDF_VERSION = "v5.3.1"

# Workaround for https://github.com/esp-rs/esp-idf-template/issues/174 
CRATE_CC_NO_DEFAULTS = "1"
