[package]
name = "settings-generator"
version = "0.1.0"
edition = "2024"

[dependencies]
rusty-esp-alarm = { path = "../" }
anyhow = "1.0.98"
clap = { version = "4.5.41", features = ["derive"] }
embedded-storage-file = "0.1.0"
tokio = { version = "1.46.1", features = ["full"] }
